"""Evidence-only corpus expansion scaffold for Visual Signature."""

from src.visual_signature.corpus_expansion.corpus_expansion_manifest import (
    assess_corpus_expansion_bundle,
    build_corpus_expansion_manifest,
    build_corpus_expansion_manifest_markdown,
    validate_corpus_expansion_bundle,
    validate_corpus_expansion_manifest,
    write_corpus_expansion_bundle,
)
from src.visual_signature.corpus_expansion.corpus_expansion_models import (
    CORPUS_EXPANSION_MANIFEST_SCHEMA_VERSION,
    CORPUS_EXPANSION_METRICS_SCHEMA_VERSION,
    CORPUS_EXPANSION_QUEUE_ITEM_SCHEMA_VERSION,
    CORPUS_EXPANSION_READINESS_SCHEMA_VERSION,
    CORPUS_EXPANSION_REVIEW_QUEUE_SCHEMA_VERSION,
    CorpusExpansionManifest,
    CorpusExpansionMetrics,
    CorpusExpansionQueueItem,
    CorpusExpansionQueueState,
    CorpusExpansionReadinessAssessment,
    CorpusExpansionReadinessStatus,
    CorpusExpansionReviewOutcome,
    CorpusExpansionReviewQueue,
    ConfidenceBucket,
    ValidationResult,
    validate_corpus_expansion_manifest_payload,
    validate_corpus_expansion_metrics_payload,
    validate_corpus_expansion_queue_item,
    validate_corpus_expansion_readiness_payload,
    validate_corpus_expansion_review_queue_payload,
)
from src.visual_signature.corpus_expansion.corpus_metrics import (
    READINESS_MAX_CONTRADICTION_RATE,
    READINESS_MAX_UNRESOLVED_RATE,
    READINESS_MIN_CATEGORY_DEPTH,
    READINESS_MIN_CONFIDENCE_BUCKETS,
    READINESS_MIN_REVIEWED_CAPTURES,
    READINESS_MIN_REVIEWER_COVERAGE,
    READINESS_MIN_TOTAL_CAPTURES,
    assess_corpus_expansion_readiness,
    build_corpus_expansion_metrics,
    corpus_expansion_metrics_markdown,
    validate_corpus_expansion_metrics,
)
from src.visual_signature.corpus_expansion.corpus_review_queue import (
    build_corpus_expansion_review_queue,
    review_queue_items_to_dicts,
    validate_corpus_expansion_review_queue,
    write_review_queue,
)
from src.visual_signature.corpus_expansion.corpus_sampling import (
    build_default_corpus_expansion_seed,
    normalize_queue_items,
    sample_review_queue_items,
)
from src.visual_signature.corpus_expansion.reviewer_workflow_pilot import (
    REVIEWER_WORKFLOW_PILOT_RECORD_TYPE,
    REVIEWER_WORKFLOW_PILOT_SCHEMA_VERSION,
    build_reviewer_workflow_pilot,
    reviewer_workflow_pilot_markdown,
    validate_reviewer_workflow_pilot_payload,
    write_reviewer_workflow_pilot,
)
from src.visual_signature.corpus_expansion.reviewer_packets import (
    build_reviewer_packets,
    validate_reviewer_packets,
    write_reviewer_packets,
)
from src.visual_signature.corpus_expansion.reviewer_viewer import (
    REVIEWER_VIEWER_RECORD_TYPE,
    REVIEWER_VIEWER_SCHEMA_VERSION,
    build_reviewer_viewer_bundle,
    validate_reviewer_viewer_bundle,
    write_reviewer_viewer_bundle,
)

build_corpus_expansion_seed = build_default_corpus_expansion_seed

__all__ = [
    "CORPUS_EXPANSION_MANIFEST_SCHEMA_VERSION",
    "CORPUS_EXPANSION_METRICS_SCHEMA_VERSION",
    "CORPUS_EXPANSION_QUEUE_ITEM_SCHEMA_VERSION",
    "CORPUS_EXPANSION_READINESS_SCHEMA_VERSION",
    "CORPUS_EXPANSION_REVIEW_QUEUE_SCHEMA_VERSION",
    "CorpusExpansionManifest",
    "CorpusExpansionMetrics",
    "CorpusExpansionQueueItem",
    "CorpusExpansionQueueState",
    "CorpusExpansionReadinessAssessment",
    "CorpusExpansionReadinessStatus",
    "CorpusExpansionReviewOutcome",
    "CorpusExpansionReviewQueue",
    "ConfidenceBucket",
    "ValidationResult",
    "READINESS_MAX_CONTRADICTION_RATE",
    "READINESS_MAX_UNRESOLVED_RATE",
    "READINESS_MIN_CATEGORY_DEPTH",
    "READINESS_MIN_CONFIDENCE_BUCKETS",
    "READINESS_MIN_REVIEWED_CAPTURES",
    "READINESS_MIN_REVIEWER_COVERAGE",
    "READINESS_MIN_TOTAL_CAPTURES",
    "REVIEWER_WORKFLOW_PILOT_RECORD_TYPE",
    "REVIEWER_WORKFLOW_PILOT_SCHEMA_VERSION",
    "REVIEWER_VIEWER_RECORD_TYPE",
    "REVIEWER_VIEWER_SCHEMA_VERSION",
    "assess_corpus_expansion_bundle",
    "assess_corpus_expansion_readiness",
    "build_corpus_expansion_manifest",
    "build_corpus_expansion_manifest_markdown",
    "build_corpus_expansion_metrics",
    "build_corpus_expansion_review_queue",
    "build_corpus_expansion_seed",
    "build_default_corpus_expansion_seed",
    "build_reviewer_packets",
    "build_reviewer_workflow_pilot",
    "build_reviewer_viewer_bundle",
    "corpus_expansion_metrics_markdown",
    "normalize_queue_items",
    "reviewer_workflow_pilot_markdown",
    "review_queue_items_to_dicts",
    "sample_review_queue_items",
    "validate_corpus_expansion_bundle",
    "validate_corpus_expansion_manifest",
    "validate_corpus_expansion_manifest_payload",
    "validate_corpus_expansion_metrics",
    "validate_corpus_expansion_metrics_payload",
    "validate_corpus_expansion_queue_item",
    "validate_corpus_expansion_readiness_payload",
    "validate_corpus_expansion_review_queue",
    "validate_corpus_expansion_review_queue_payload",
    "validate_reviewer_packets",
    "validate_reviewer_workflow_pilot_payload",
    "validate_reviewer_viewer_bundle",
    "write_corpus_expansion_bundle",
    "write_reviewer_packets",
    "write_reviewer_workflow_pilot",
    "write_reviewer_viewer_bundle",
    "write_review_queue",
]
